LGA-455 Simplify cyclomatic complexity of the 'get_cait_params' function
ministryofjustice/cla_public pull request #1001
Opened 2020-09-09 08:39 UTC by mayowaadeniyi

## What does this pull request do?

- Create a class and place functionality into separate methods in the class

## Any other changes that would benefit highlighting?

Intentionally left blank.

## Checklist

- [ ] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"

2020-09-11 11:06 UTC, exonian requested changes
I like where this is going.
I think I'd be interested to see if even more could be moved into that class, so we could either:
a) just initialise it, do minimal further work to it, and then return its output, or, possibly better yet
b) have the class _be_ a dict-like object (rather than contain one), so we'd actually be returning an instance of the class itself (think of like a `Counter` or something, for an object that is itself a dict-like object but also has the stuff within itself to set its values as needed).

If you can think of any ways of simplifying the config wrangling, too, that'd be neat, as it's a bit verbose atm but none necessarily spring to my mind

2020-09-11 11:06 UTC, exonian commented on cla_public/apps/checker/cait_intervention.py
> +        params_class.create_css_and_js_params(css_config, js_config)
Is there any need to do these separately? Could we combine them into one call? Could we do them on `init`, even?

2020-09-14 08:24 UTC, mayowaadeniyi commented on cla_public/apps/checker/cait_intervention.py
> +    except ConfigException:
Done

2020-09-16 14:04 UTC, exonian approved these changes

2020-09-16 16:22 UTC, merged