LGA-3235 Pull shared laa ips
ministryofjustice/cla_public pull request #1276
Opened 2024-08-21 08:13 UTC by digitalali-moj

## What does this pull request do?
https://dsdmoj.atlassian.net/jira/software/c/projects/LGA/issues/LGA-3235

Pull IP addresses for repository as a proof of concept. Feedback welcome. Sorry no Jira ticket on commit as this was something that was born in LAA eng leadership, but if we are happy with this approach for pulling IPs, which will vary depending on app, we can use this ticket to track the work and pull into sprint.

## Any other changes that would benefit highlighting?

The IP address list will be updated with all the new IP addresses shortly.
https://raw.githubusercontent.com/ministryofjustice/laa-ip-allowlist/main/cidrs.txt

CLA Public only applies this to staging, so it's a good place to try this.

## Checklist

- [x] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"

2024-08-21 10:36 UTC, said-moj submitted a review, later dismissed

2024-08-22 08:59 UTC, BenMillar-MOJ requested changes
Looks good, really great approach to this!
Could we have some comments to remind our future selves how and where the IP whitelist is populated from.

Many thanks! 😄

2024-08-22 08:59 UTC, BenMillar-MOJ commented on bin/staging_deploy.sh
Could we add a comment here explaining how this file is reformatted please?

2024-08-22 13:39 UTC, BenMillar-MOJ approved these changes

2024-08-22 17:19 UTC, digitalali-moj commented on bin/production_deploy.sh
> +  --set-string sharedIPRangesLAA="Any IP allowed but keep this string" \
This is for the helper.tpl part to work even if there's no IPs, a bit like the pingdom IPs even though it's not needed in prod.

2024-08-23 09:33 UTC, said-moj approved these changes

2024-08-23 09:34 UTC, merged